load("2. Baseline Characteristics/final_baseline.RData")
baseline_ENA$Index.Drug <- 0
baseline_SV$Index.Drug <- 1
baseline <- rbind(baseline_SV, baseline_ENA)
pts <- cbind.data.frame(Reference.Key.=baseline$Reference.Key., Index.Date=baseline$Index.Date, Index.Drug=baseline$Index.Drug)
rm(list = ls(pattern="^baseline"))

load("Data/Combined data/Rx_entresto.Rdata")
RX <- Entresto_Rx[Entresto_Rx$Reference.Key. %in% pts$Reference.Key.,]
rm(Entresto_Rx)
load("Data/Combined data/Rx_enalapril.Rdata")
RX <- rbind(RX, Enalapril_rx[Enalapril_rx$Reference.Key. %in% pts$Reference.Key.,])
rm(Enalapril_rx)

RX <- merge(RX, pts, by="Reference.Key.")
#RX <- RX[RX$Prescription.Start.Date. < RX$Index.Date & RX$Prescription.Start.Date. >= (RX$Index.Date - 365),]
RX <- RX[RX$Prescription.Start.Date. < RX$Index.Date & RX$Prescription.Start.Date. > (RX$Index.Date - 365),]

# meds.acei <- "RAMIPRIL|PERINDOPRIL|PERINDOPRIL|BENAZEPRIL|CAPTOPRIL|LISINOPRIL|LISINOPRIL|FOSINOPRIL|QUINAPRIL|IMIDAPRIL|TRITACE|ACERTIL|PREDONIUM|FORTEKOR|ZESTRIL|ZESTORETIC|MONOPRIL|ACCUPRIL"
# meds.arb <-"LOSARTAN|LOSARTAN|VALSARTAN|IRBESARTAN|CANDESARTAN|TELMISARTAN|EPROSARTAN|OLMESARTAN|AZILSARTAN|COZAAR|HYZAAR|DIOVAN|CO-DIOVAN|APROVEL|COAPROVEL|BLOPRESS|BLOPRESS PLUS|MICARDIS|TEVETEN|OLMETEC|AZOREN|EDARBI|EDARBYCLOR|LOSACOR HCT|ATACAND"
# meds.bbk <-"METOPROLOL|ATENOLOL|ATENOLOL|CARVEDILOL|PROPRANOLOL|SOTALOL|LABETALOL|ACEBUTOLOL|NADOLOL|BISOPROLOL|BISOPROLOL|PINDOLOL|OXPRENOLOL|NEBIVOLOL|CELIPROLOL|BETALOC|TENOREN|TENORETIC|DILATREND|SOTACOR|TRANDATE|CONCOR|LODOZ|VISKEN|CORBETON|NEBILET|SELECTOL|TENORET|MONOCOR"
# meds.diuretic <- "METHYCLOTHIAZIDE|INDAPAMIDE|HYDROCHLOROTHIAZIDE|METOLAZONE|BENDROFLUAZIDE|CHLORTHALIDONE|FRUSEMIDE|BUMETANIDE|AMILORIDE|SPIRONOLACTONE|EPLERENONE|AMILORIDE|TRIAMTERENE|ENDURON|NATRILIX|DIULO|LASIX|BURINEX|ALDACTONE|INSPRA|MODURETIC|DYAZIDE|AMILORETIC|APO-TRIAZIDE"
# meds.digoxin <- "Digoxin|lanoxin"
# meds.ivabradine <- "Coralan|ivabradine"
# meds.mra <- "AMILORIDE|SPIRONOLACTONE|EPLERENONE|ALDACTONE|INSPRA"
# meds.dobutamine <- "Dobutel|dobutamine"
# meds.epi <- "Epinephrine|norepinephrine|septanest"
# meds.milrinone <- "PRIMACOR|milrinone"
# meds.levosimendan <- "Levosimendan|simdax"
# meds.vaptans <- "Tolvaptan|samsca|jinarc"
# meds.statins <- "ATORVASTATIN|ROSUVASTATIN|SIMVASTATIN|LIPITOR|CRESTOR|ZOCOR"
# meds.ccb <- "NIFEDIPINE|AMLODIPINE|DILTIAZEM|VERAPAMIL|FELODIPINE|NIMODIPINE|LACIDIPINE|LERCANIDIPINE|ADALAT|NORVASC|HERBESSER|TIAZAC|ISOPTIN|PLENDIL|NIMOTOP|LACIPIL|ZANIDIP"
# meds.arrthy <- "AMIODARONE|DRONEDARONE|DISOPYRAMIDE|FLECAINIDE|PROPAFENONE|MEXILETINE|CORDARONE|MULTAQ|RYTHMODAN|TAMBOCOR|RYTMONORM"
# meds.plt <- "ASPIRIN|DIPYRIDAMOLE|CLOPIDOGREL|CLOPIDOGREL|TICLOPIDINE|EPTIFIBATIDE|TIROFIBAN|PRASUGREL|TICAGRELOR|CARTIA|CARDIPRIN|AGGRENOX|PLAVIX|COPLAVIX|APLAKET|INTEGRILIN|AGGRASTAT|EFFIENT|BRILINTA"
# meds.throm <- "ENOXAPARIN|HEPARIN|NADROPARIN|TINZAPARIN|DALTEPARIN|BEMIPARIN|FONDAPARINUX|WARFARIN|DABIGATRAN|RIVAROXABAN|APIXABAN|CLEXANE|FRAXIPARINE|INNOHEP|FRAGMIN|HIBOR|ARIXTRA|PRADAXA|XARELTO|ELIQUIS"
# meds.angina <- "GLYCERYL TRINITRATE|ISOSORBIDE MONONITRATE|ISOSORBIDE DINITRATE|NITRODERM|ELANTAN|ISOKET"
# meds.ranolazine <- "Ranolazine|renexa"

meds.ras <- "LOSARTAN|LOSARTAN|VALSARTAN|IRBESARTAN|CANDESARTAN|TELMISARTAN|EPROSARTAN|OLMESARTAN|AZILSARTAN|COZAAR|HYZAAR|DIOVAN|CO-DIOVAN|APROVEL|COAPROVEL|BLOPRESS|BLOPRESS PLUS|MICARDIS|TEVETEN|OLMETEC|AZOREN|EDARBI|EDARBYCLOR|LOSACOR HCT|ATACAND|SARTAN|VALSARTAN|RAMIPRIL|PERINDOPRIL|PERINDOPRIL|BENAZEPRIL|CAPTOPRIL|LISINOPRIL|LISINOPRIL|FOSINOPRIL|QUINAPRIL|IMIDAPRIL|TRITACE|ACERTIL|PREDONIUM|FORTEKOR|ZESTRIL|ZESTORETIC|MONOPRIL|ACCUPRIL|TANATRIL|COVERSYL|PRIL|Aliskiren|Tekturna|Rasilez"
meds.bbk <- "METOPROLOL|ATENOLOL|ATENOLOL|CARVEDILOL|PROPRANOLOL|SOTALOL|LABETALOL|ACEBUTOLOL|NADOLOL|BISOPROLOL|BISOPROLOL|PINDOLOL|OXPRENOLOL|NEBIVOLOL|CELIPROLOL|LOL"
meds.diuretic <- "METHYCLOTHIAZIDE|INDAPAMIDE|HYDROCHLOROTHIAZIDE|METOLAZONE|BENDROFLUAZIDE|CHLORTHALIDONE|FRUSEMIDE|BUMETANIDE|AMILORIDE|SPIRONOLACTONE|PLERENONE|AMILORIDE|TRIAMTERENE|ENDURON|NATRILIX|DIULO|LASIX|BURINEX|ALDACTONE|INSPRA|MODURETIC|DYAZIDE|AMILORETIC|AMILZIDE|APO-TRIAZIDE"
meds.digoxin <- "Digoxin|lanoxin"
meds.mra <- "spironolactone|aldactone|eplerenone"
meds.statins <- "[^n][^y]statin|fibrate|gemfibrozil"
meds.ccb <- "NIFEDIPINE|AMLODIPINE|DILTIAZEM|VERAPAMIL|FELODIPINE|NIMODIPINE|LACIDIPINE|LERCANIDIPINE|ADALAT|NORVASC|HERBESSER|TIAZAC|ISOPTIN|PLENDIL|NIMOTOP|LACIPIL|ZANIDIP"
meds.arrthy <- "AMIODARONE|DRONEDARONE|DISOPYRAMIDE|FLECAINIDE|PROPAFENONE|MEXILETINE|CORDARONE|MULTAQ|RYTHMODAN|TAMBOCOR|RYTMONORM|PROCAINAMIDE|QUINIDINE|Pronestyl|Procan|Quinidex|Quinora|Cardioquin|Quinaglute"
meds.throm <- "ENOXAPARIN|CLEXANE|HEPARIN|NADROPARIN|FRAXIPARINE|TINZAPARIN|INNOHEP|DALTEPARIN|FRAGMIN|BEMIPARIN|HIBOR|FONDAPARINUX|ARIXTRA|WARFARIN|DABIGATRAN|PRADAXA|RIVAROXABAN|XARELTO|APIXABAN|ELIQUIS|ASPIRIN|CARTIA|ASPIRIN|GLYCINE|CARDIPRIN|DIPYRIDAMOLE|ASPIRIN|AGGRENOX|CLOPIDOGREL|PLAVIX|CLOPIDOGREL|ASPIRIN|COPLAVIX|TICLOPIDINE|APLAKET|EPTIFIBATIDE|INTEGRILIN|TIROFIBAN|AGGRASTAT|PRASUGREL|EFFIENT|TICAGRELOR|BRILINTA"
meds.dm <- "INSULIN NEUTRAL|ACTRAPID HUMULIN R|INSULIN LISPRO|HUMALOG|INSULIN ASPART|NOVORAPID|INSULIN HUMAN|INSULIN ISOPHANE|MIXTARD 30|INSULIN ISOPHANE|PROTAPHANE|HUMULIN N|INSULIN ZINC|MONOTARD|ULTRATARD|INSULIN|HUMAN INSULIN ISOPHANE|HUMULIN|GLARGINE|LANTUS|GLIPIZIDE|MINIDIAB|GLICLAZIDE|DIAMICRON|GLIBENCLAMIDE|METFORMIN|GLUCOVANCE|GLIBENCLAMIDE|DAONIL|TOLBUTAMIDE|GLIMEPIRIDE|AMARYL|METFORMIN|GLUCOPHAGE|ACARBOSE|GLUCOBAY|ROSIGLITAZONE|AVANDIA|ROSIGLITAZONE|AVANDAMET|PIOGLITAZONE|ACTOS|ACTOSMET|SAXAGLIPTIN|ONGLYZA|KOMBIGLYZE|JANUVIA|JANUMET|TRAJENTA|LINAGLIPTIN|TRAJENTA DUO|EMPAGLIFLOZIN|GLYXAMBI|VILDAGLIPTIN|GALVUS|ALOGLIPTIN|NESINA|NESINA MET|EXENATIDE|BYETTA|BYDUREON|LIRAGLUTIDE|VICTOZA|REPAGLINIDE|NOVONORM|NATEGLINIDE|STARLIX|GLIFLOZIN|GLIPTIN|GLUTIDE|ENATIDE"
code.ras <- "CAND|IRBE|LOSA|TELM|VALS|CAPT|LISI|PERI|RAMI|ALIS"
code.mra <- "SPIR"
code.statins <- "ATOR|ROSU|SIMV|GEMF|FENO"
code.ccb <- "AMLO|DILT|FEL|NIFE"
excl.ras <- "ENTRESTO"
excl.bbk <- "TIMOLOL|BETAXOLOL|CARTEOLOL|Ticagrelol"

# Manual fixes
RX <- RX[!(grepl("^FRUSEMIDE", RX$Drug.Name.) & grepl("^ROSU", RX$Drug.Item.Code.)),]

meds <- pts
for(medtyp in ls(pattern = "^meds[.]")) {
  rx <- RX[grepl(get(medtyp), RX$Drug.Name., ignore.case = T),]
  codetyp <- paste0("code.", substr(medtyp,6,nchar(medtyp)))
  if(!is.null(get0(codetyp))) rx <- rbind(rx, RX[grepl(get(codetyp), RX$Drug.Item.Code.),])
  excltyp <- paste0("excl.", substr(medtyp,6,nchar(medtyp)))
  if(!is.null(get0(excltyp))) rx <- rx[!grepl(get(excltyp), rx$Drug.Name.),]
  meds[,medtyp] = as.numeric(meds$Reference.Key. %in% rx$Reference.Key.)
}

save(meds, file = "supp_meds.RData")
rm(list = ls(pattern = "^meds|^code|^excl|^medtyp$|^rx$"))
